apiVersion: apps/v1
kind: Deployment
metadata:
  name: container2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container2
  template:
    metadata:
      labels:
        app: container2
    spec:
      nodeSelector:
        kubernetes.io/hostname: gke-gke-standard-clu-primary-node-poo-bb4eedc1-gpsc  # Ensure the pod runs on the correct node
      containers:
      - name: container2
        image: us-central1-docker.pkg.dev/k8s-microservices-project/k8-container2-repo/container2:latest
        ports:
        - containerPort: 5001
        volumeMounts:
        - name: storage
          mountPath: "/Navya_PV_dir"
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: navya-pvc
