apiVersion: v1
kind: PersistentVolume
metadata:
  name: navya-pv
spec:
  capacity:
    storage: 1Gi  # 1GB storage
  accessModes:
    - ReadWriteMany  # Allow multiple pods to read/write
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/Navya_PV_dir"  # Mount the directory
